### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by joker234** [koebi/potypo#2]
please add a LICENSE file according to https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by joker234** [comment]
Maybe you should update the classifiers in `setup.py`, if you change the license.
https://github.com/koebi/potypo/blob/c6c40e0f917b3355618c53ad4c338c84ea62d067/setup.py#L25

**Comment by koebi** [comment]
Ah, I seem to already have a license and it should just be reflected in the project itself ;)
